version: '3.1'

services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    depends_on:
      - db
    ports:
      - "5441:5432"
    networks:
      - net
  agent:
    deploy:
      mode: replicated
      replicas: 1  # ЗДЕСЬ МОЖНО ИЗМЕНИТЬ КОЛИЧЕСТВО АГЕНТОВ
    build:
      context: .
      dockerfile: agent.Dockerfile
    networks:
      - net
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calc_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
networks:
  net:
    driver: bridge

volumes:
  db: